-- Create custom enum types
CREATE TYPE user_role AS ENUM ('teacher', 'student', 'admin');
CREATE TYPE session_status AS ENUM ('scheduled', 'active', 'ended', 'cancelled');
CREATE TYPE session_method AS ENUM ('code', 'qr', 'manual', 'auto');
CREATE TYPE attendance_status AS ENUM ('present', 'absent', 'late', 'excused');
CREATE TYPE check_method AS ENUM ('code', 'qr', 'manual', 'auto');
CREATE TYPE assignment_type AS ENUM ('homework', 'project', 'quiz', 'exam', 'lab');
CREATE TYPE submission_format AS ENUM ('file', 'text', 'both');
CREATE TYPE assignment_status AS ENUM ('draft', 'published', 'closed');
CREATE TYPE submission_status AS ENUM ('draft', 'submitted', 'graded', 'returned');
CREATE TYPE notification_type AS ENUM ('attendance', 'assignment', 'grade', 'announcement', 'system');
CREATE TYPE priority_level AS ENUM ('low', 'normal', 'high', 'urgent');
CREATE TYPE reference_type AS ENUM ('attendance_session', 'assignment', 'classroom');
CREATE TYPE file_category AS ENUM ('avatar', 'assignment', 'submission', 'classroom', 'other');
CREATE TYPE permission_type AS ENUM ('view', 'download', 'edit', 'delete');
CREATE TYPE event_type AS ENUM ('holiday', 'exam', 'break', 'semester_start', 'semester_end', 'other');
CREATE TYPE message_type AS ENUM ('private', 'classroom', 'announcement');
CREATE TYPE risk_level AS ENUM ('low', 'medium', 'high');
CREATE TYPE metric_type AS ENUM ('attendance_rate', 'assignment_score', 'exam_score', 'participation');
CREATE TYPE search_type AS ENUM ('students', 'assignments', 'attendance', 'classrooms', 'general');
CREATE TYPE device_platform AS ENUM ('ios', 'android', 'web');
CREATE TYPE data_type_setting AS ENUM ('string', 'number', 'boolean', 'json');